version: '3.8'

services:
  fraud-detection-api:
    build:
      context: .
      dockerfile: Dockerfile.fallback
    container_name: tasks9-fraud-detection-fallback
    ports:
      - "8000:8000"
    environment:
      # API Configuration
      API_HOST: "0.0.0.0"
      API_PORT: "8000"
      ENVIRONMENT: "development"
      DEBUG: "false"
      
      # Fallback Configuration
      USE_MOCK_MODEL: "true"
      MODEL_LOAD_TIMEOUT: "10"
      
      # MLflow Configuration (will be ignored in mock mode)
      MLFLOW_TRACKING_URI: "http://mlflow.darveter.com"
      MLFLOW_EXPERIMENT_NAME: "fraud_detection_experiment"
      MLFLOW_MODEL_NAME: "fraud_model_production"
      MLFLOW_MODEL_STAGE: "Production"
      
      # S3/MinIO Configuration (will be ignored in mock mode)
      AWS_ACCESS_KEY_ID: "minio"
      AWS_SECRET_ACCESS_KEY: "minio123"
      AWS_DEFAULT_REGION: "us-east-1"
      MLFLOW_S3_ENDPOINT_URL: "http://minio.darveter.com:9000"
      
      # Model Configuration
      MODEL_NAME: "fraud_detection_model"
      MODEL_VERSION: "mock-v1.0"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fraud-api.rule=Host(`fraud-api.localhost`)"
      - "traefik.http.services.fraud-api.loadbalancer.server.port=8000"
