apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: "1.17.0"
    helm:
      values: |
        ingress:
          apiServer:
            enabled: true
            ingressClassName: "system-ingress"
            hosts:
              - "airflow.darveter.com"
          web:
            enabled: true
            ingressClassName: "system-ingress"
            hosts:
              - "airflow.darveter.com"

        # Обязательные параметры для Argo CD согласно официальной документации
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false

        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          # Аннотация для автоматического запуска миграций БД при синхронизации
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync

        # Настройки пользователя по умолчанию (администратора)
        webserver:
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            email: admin@example.com
            firstName: admin
            lastName: user
            password: password

        # Настройки PostgreSQL с указанием storageClass
        postgresql:
          enabled: true
          auth:
            postgresPassword: postgres
          primary:
            persistence:
              enabled: true
              storageClass: local-path
              accessModes:
                - ReadWriteOnce
              size: 8Gi

        # Настройки Redis (базовая конфигурация без persistence)
        redis:
          enabled: true

        # Настройки логов - отключены для совместимости с local-path
        # logs:
        #   persistence:
        #     enabled: true
        #     size: 1Gi
        #     storageClassName: nfs-csi

        # Использование KubernetesExecutor для избежания проблем с shared storage
        executor: KubernetesExecutor

        # Использование кастомного образа
        images:
          airflow:
            repository: mrhagal/my-airflow-mlops
            tag: v4
            pullPolicy: Always

        # Отключение persistence для компонентов
        workers:
          persistence:
            enabled: false

        triggerer:
          persistence:
            enabled: false

        dags:
          # Отключаем persistence в пользу Git Sync
          # persistence:
          #   enabled: true               # включаем хранение DAG-ов на PVC
          #   size: 1Gi                   # нужный размер
          #   storageClassName: nfs-csi

          gitSync:
            enabled: true
            repo: https://github.com/DarVeter24/mlopstraining.git
            branch: main            # в этой версии чарта используется branch
            # depth: 1
            subPath: "Tasks10/dag"  # проверь, что папка существует
            # wait: 60
            # period: 60s
            # maxFailures: 0
            # uid: 65533


  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
