apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks10-ml-service-config
  namespace: mlops-tasks10
  labels:
    app: fraud-detection-api
    component: config
data:
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  ENVIRONMENT: "production"
  DEBUG: "false"
  
  # MLflow Configuration  
  MLFLOW_TRACKING_URI: "http://mlflow.darveter.com"
  MLFLOW_EXPERIMENT_NAME: "fraud_detection_experiment"
  MLFLOW_MODEL_NAME: "fraud_model_production"
  MLFLOW_MODEL_STAGE: "Production"
  
  # S3/MinIO Configuration
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: "http://minio.darveter.com:9000"
  
  # Fallback Configuration
  USE_MOCK_MODEL: "true"
  MODEL_LOAD_TIMEOUT: "30"
  
  # Model Configuration
  MODEL_NAME: "fraud_detection_model"
  MODEL_VERSION: "latest"
