apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks10-ml-service
  namespace: argocd
  labels:
    app: tasks10-ml-api
    project: tasks10-mlops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DarVeter24/mlopstraining.git
    targetRevision: HEAD
    path: Tasks10/argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-tasks10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    managedFieldsManagers:
    - kube-controller-manager
