name: Tasks10 Security Scan

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'Tasks10/**'  # Запускается только при изменениях в Tasks10/
  pull_request:
    branches: [ main ]
    paths:
      - 'Tasks10/**'  # Запускается только при изменениях в Tasks10/
  schedule:
    # Запускаем каждую неделю в понедельник в 02:00 UTC
    - cron: '0 2 * * 1'

jobs:
  # Сканирование зависимостей на уязвимости
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit semgrep
        
    - name: Run Safety (dependency vulnerability scan)
      run: |
        cd Tasks10
        pip install -r requirements.txt
        safety check --json --output safety-report.json || true
        
    - name: Run Bandit (security linter)
      run: |
        cd Tasks10
        bandit -r src/ -f json -o bandit-report.json || true
        
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: tasks10-security-reports
        path: |
          Tasks10/safety-report.json
          Tasks10/bandit-report.json

  # Сканирование Docker образа на уязвимости
  docker-security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        cd Tasks10
        docker build -t tasks10-ml-api:security-scan .
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'tasks10-ml-api:security-scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Статический анализ кода
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
