apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tasks9-fraud-detection
  namespace: tasks9-mlops

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: fraud-detection-api
  project: tasks9-mlops
  managed-by: argocd

commonAnnotations:
  version: v1.0.0
  description: "MLOps fraud detection service"

images:
- name: ghcr.io/darveter24/mlopstraining/tasks9-fraud-detection-api
  newTag: latest

namespace: tasks9-mlops

replicas:
- name: tasks9-fraud-detection-api
  count: 2
